<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">

  <xacro:macro name="box_inertia" params="b_mass b_length b_width b_height">
    <inertial>
      <mass value="${b_mass}"/>
      <inertia ixx="${b_mass*(b_length*b_length+b_height*b_height)/12}" ixy="0.0" ixz="0.0"
               iyy="${b_mass*(b_width*b_width+b_height*b_height)/12}" iyz="0.0"
               izz="${b_mass*(b_length*b_length+b_width*b_width)/12}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="c_mass c_radius c_height">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${c_mass}"/>
      <inertia ixx="${c_mass*(3*c_radius*c_radius+c_height*c_height)/12}" ixy="0.0" ixz="0.0"
               izz="${c_mass*(3*c_radius*c_radius+c_height*c_height)/12}" iyz="0.0"
               iyy="${c_mass*c_radius*c_radius/2}"/>
    </inertial>
  </xacro:macro>

  <xacro:property name="base_link_mass" value="3.0" /><!-- please correct this -->
  <xacro:property name="base_link_length" value="0.4" />
  <xacro:property name="base_link_width" value="0.4" />
  <xacro:property name="base_link_height" value="0.1" />
  <xacro:property name="wheel_mass" value="20.0" /><!-- please correct this -->
  <xacro:property name="wheel_radius" value="0.0315" /><!-- please correct this -->
  <xacro:property name="track" value="0.17" />
  <xacro:property name="clearance" value="0.025" />


  <joint name="base_to_root" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_link_height/2+clearance}" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="base_link_geometry">
    <geometry>
      <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:macro>

  <link name="base_link">
    <visual>
      <xacro:base_link_geometry />
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>
    <collision>
      <xacro:base_link_geometry />
    </collision>
    <xacro:box_inertia
     b_mass="${base_link_mass}"
     b_length="${base_link_length}"
     b_width="${base_link_width}"
     b_height="${base_link_height}"/>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/RustySteel</material>
  </gazebo>

  <xacro:macro name="wheel_joint" params="w_name origin_x origin_y origin_z geometry_yaw">
    <link name="${w_name}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2+geometry_yaw}"/>
        <material name="black">
          <color rgba="0.2 0.2 0.2 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <xacro:cylinder_inertia
        c_mass="${wheel_mass}"
        c_radius="${wheel_radius}"
        c_height="${wheel_height}"/>
    </link>

    <joint name="base_to_${w_name}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${w_name}_wheel"/>
      <axis xyz="0 1 0"/>
      <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>

    </joint>

    <gazebo reference="${w_name}_wheel">
      <mu1 value="0.5"/>
      <mu2 value="0.5"/>
      <fdir1 value="0 0 0"/>

      <!--kp value="10000000.00" />
      <kd value="1.00" />
      <minDepth value="0.001"/-->

      <maxContacts value="1"/>
      <turnGravityOff>false</turnGravityOff>
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <transmission name="${w_name}_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="base_to_${w_name}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="base_to_${w_name}_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>



  <xacro:wheel_joint
    w_name="l_m"
    origin_y="${track/2}"
    origin_x="0"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="0"/>

  <xacro:wheel_joint
    w_name="r_m"
    origin_y="${-track/2}"
    origin_x="0"
    origin_z="${wheel_radius-base_link_height/2-clearance}"
    geometry_yaw="${pi}"/>

  <!-- GPS -->
  <link name="gps_link"></link>

  <joint name="gps_joint" type="fixed">
    <parent link="ctrlbox_link"/>
    <child link="gps_link"/>
    <origin xyz="0 -0.1 0.105" rpy="0 0 0"/>
  </joint>

  <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
        <!--controlPeriod>0.005</controlPeriod-->
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        <legacyModeNS>true</legacyModeNS>
      </plugin>
  </gazebo>


</robot>
